import type { Metadata } from "next";
import localFont from "next/font/local";
import Header from "./_components/Header/Header";
import Toast from "./_components/Toast";
import "./globals.css";
import Nav from "./_components/Header/Nav";
import HeaderActions from "./_components/Header/HeaderActions";
import QueryClientProvider from "./_providers/QueryClientProvider";
import { ReactQueryDevtools } from "@tanstack/react-query-devtools";
import PrevPageButton from "./_components/Header/PrevPageButton";

const iran_yekan = localFont({ src: "_fonts/Qs_Iranyekan.ttf" });

export const metadata: Metadata = {
  title: "نماوا:‌تماشای آنلاین فیلم و سریال",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fa-IR">
      <body className={`${iran_yekan.className} antialiased`}>
        <QueryClientProvider>
          <ReactQueryDevtools initialIsOpen={false} />
          <Toast />
          <Header>
            <PrevPageButton />
            <Nav />
            <HeaderActions />
          </Header>
          <main>{children}</main>
        </QueryClientProvider>
      </body>
    </html>
  );
}
